drop table if exists j_task;
create table j_task (
	id bigint generated by default as identity,
	title varchar(128) not null,
	description varchar(255),
	user_id bigint not null,
    primary key (id)
);

drop table if exists j_user;
create table j_user (
	id bigint generated by default as identity,
	login_name varchar(64) not null unique,
	name varchar(64) not null,
	password varchar(255) not null,
	salt varchar(64) not null,
	roles varchar(255) not null,
	register_date timestamp not null,
	primary key (id)
);


drop table if exists j_code_info;
CREATE TABLE j_code_info (
  ID varchar(32) NOT NULL,
  CODE varchar(32) NOT NULL,
  CODE_VALUE varchar(64) NOT NULL,
  INDEX_NO int(11) DEFAULT NULL,
  LOCAL varchar(10) DEFAULT NULL,
  REMARK varchar(128) DEFAULT NULL,
  CODE_TYPE varchar(32) NOT NULL,
  PRIMARY KEY (ID)
); 

drop table if exists j_code_type;
CREATE TABLE j_code_type (
  ID varchar(32) NOT NULL,
  REMARK varchar(128) DEFAULT NULL,
  TYPE_CODE varchar(32) NOT NULL,
  TYPE_NAME varchar(64) NOT NULL,
  GROUP_NAME varchar(32) DEFAULT NULL,
  PRIMARY KEY (ID),
  UNIQUE (TYPE_CODE)
); 


drop table if exists j_user_auth;
CREATE TABLE j_user_auth (
  ID varchar(32) NOT NULL,
  ACCOUNT_EXPIRE_DATETIME char(19) DEFAULT NULL,
  CREATED_DATETIME char(19) DEFAULT NULL,
  CREATOR_ID varchar(32) DEFAULT NULL,
  DEL_FLAG char(1) NOT NULL DEFAULT '0',
  FAILED_LOGIN_COUNT decimal(5,0) DEFAULT NULL,
  LAST_LOGIN_DATETIME char(19) DEFAULT NULL,
  LAST_LOGIN_IP varchar(25) DEFAULT NULL,
  LAST_MODIFIED_DATETIME char(19) DEFAULT NULL,
  LAST_MODIFIER_ID varchar(32) DEFAULT NULL,
  LOGIN_DATETIME char(19) DEFAULT NULL,
  LOGIN_ID varchar(32) DEFAULT NULL,
  LOGIN_IP varchar(25) DEFAULT NULL,
  MAX_FAILED_LOGIN_COUNT decimal(5,0) DEFAULT NULL,
  PASSWD varchar(64) DEFAULT NULL,
  PASSWD_EXPIRE_DATETIME char(19) DEFAULT NULL,
  PASSWD_EXPIRE_DAYS decimal(5,0) DEFAULT NULL,
  STAFF_ID varchar(32) DEFAULT NULL,
  PRIMARY KEY (ID)
);


drop table if exists j_resource;
CREATE TABLE j_resource (
  ID varchar(32) NOT NULL,
  CREATED_DATETIME char(19) DEFAULT NULL,
  CREATOR_ID varchar(32) DEFAULT NULL,
  DEL_FLAG char(1) NOT NULL DEFAULT '0',
  LAST_MODIFIED_DATETIME char(19) DEFAULT NULL,
  LAST_MODIFIER_ID varchar(32) DEFAULT NULL,
  ext1 varchar(256) DEFAULT NULL,
  ext2 varchar(64) DEFAULT NULL,
  ext3 varchar(64) DEFAULT NULL,
  ext4 varchar(64) DEFAULT NULL,
  ext5 varchar(64) DEFAULT NULL,
  ext6 varchar(64) DEFAULT NULL,
  ext7 varchar(64) DEFAULT NULL,
  ext8 varchar(64) DEFAULT NULL,
  ext9 varchar(64) DEFAULT NULL,
  OTHER_EXTS varchar(256) DEFAULT NULL,
  PARENT_RES_CODE varchar(256) DEFAULT NULL,
  PARENT_RES_TYPE_CODE varchar(32) DEFAULT NULL,
  remark varchar(128) DEFAULT NULL,
  RES_CODE varchar(256) NOT NULL,
  RES_NAME varchar(64) DEFAULT NULL,
  RES_SEQUENCE decimal(5,0) NOT NULL DEFAULT '0',
  RES_TYPE_CODE varchar(32) NOT NULL,
  status varchar(10) DEFAULT NULL,
  level decimal(5,0) NOT NULL DEFAULT '0',
  PRIMARY KEY (ID)
);


drop table if exists j_res_type;
CREATE TABLE j_res_type (
  ID varchar(32) NOT NULL,
  CREATED_DATETIME char(19) DEFAULT NULL,
  CREATOR_ID varchar(32) DEFAULT NULL,
  DEL_FLAG char(1) NOT NULL DEFAULT '0',
  LAST_MODIFIED_DATETIME char(19) DEFAULT NULL,
  LAST_MODIFIER_ID varchar(32) DEFAULT NULL,
  PARENT_RES_TYPE_CODE varchar(32) DEFAULT NULL,
  REMARK varchar(128) DEFAULT NULL,
  RES_EXTS longtext,
  RES_TYPE_CODE varchar(32) NOT NULL,
  RES_TYPE_EDITABLE varchar(1) DEFAULT NULL,
  RES_TYPE_ICON varchar(256) DEFAULT NULL,
  RES_TYPE_NAME varchar(64) DEFAULT NULL,
  RES_TYPE_SEQ decimal(5,0) NOT NULL DEFAULT '0',
  PRIMARY KEY (ID)
);


drop table if exists j_res_type_perm;
CREATE TABLE j_res_type_perm (
  ID varchar(32) NOT NULL,
  CREATED_DATETIME char(19) DEFAULT NULL,
  CREATOR_ID varchar(32) DEFAULT NULL,
  DEL_FLAG char(1) NOT NULL DEFAULT '0',
  LAST_MODIFIED_DATETIME char(19) DEFAULT NULL,
  LAST_MODIFIER_ID varchar(32) DEFAULT NULL,
  DEFAULT_FLAG char(1) NOT NULL DEFAULT '0',
  PERM_ALIAS varchar(64) DEFAULT NULL,
  PERM_CODE varchar(32) NOT NULL,
  PERM_NAME varchar(64) DEFAULT NULL,
  PERM_PRIORITY decimal(5,0) NOT NULL DEFAULT '0',
  PERM_SEQ decimal(5,0) NOT NULL DEFAULT '0',
  REMARK varchar(128) DEFAULT NULL,
  RES_TYPE_CODE varchar(32) NOT NULL,
  PRIMARY KEY (ID)
);



drop table if exists j_res_relation;
CREATE TABLE j_res_relation (
  ID varchar(32) NOT NULL,
  CREATED_DATETIME char(19) DEFAULT NULL,
  CREATOR_ID varchar(32) DEFAULT NULL,
  DEL_FLAG char(1) NOT NULL DEFAULT '0',
  LAST_MODIFIED_DATETIME char(19) DEFAULT NULL,
  LAST_MODIFIER_ID varchar(32) DEFAULT NULL,
  CORE_RES_CODE varchar(256) NOT NULL,
  CORE_RES_TYPE varchar(32) NOT NULL,
  RELATED_RES_CODE varchar(256) NOT NULL,
  RELATED_RES_TYPE varchar(32) NOT NULL,
  PRIMARY KEY (ID)
);

drop table if exists j_res_relation;
CREATE TABLE j_authorization (
  ID varchar(32) NOT NULL,
  APPROVE_STATUS varchar(1) DEFAULT NULL,
  AUTH_TYPE varchar(1) DEFAULT NULL,
  CREATED_DATETIME varchar(19) DEFAULT NULL,
  CREATOR_ID varchar(32) DEFAULT NULL,
  DEL_FLAG varchar(1) DEFAULT NULL,
  DESCENT_KIND varchar(32) DEFAULT NULL,
  LAST_MODIFIED_DATETIME varchar(19) DEFAULT NULL,
  LAST_MODIFIED_ID varchar(32) DEFAULT NULL,
  PERM_CODES varchar(32) DEFAULT NULL,
  RES_CODE varchar(256) DEFAULT NULL,
  RES_TYPE_CODE varchar(32) DEFAULT NULL,
  ROLE_CODE varchar(32) DEFAULT NULL,
  PRIMARY KEY (ID)
);